a=int(input("Marks of student 1="))
b=int(input("Marks of student 2="))
c=int(input("Marks of student 3="))
d=int(input("Marks of student 4="))
e=int(input("Marks of student 5="))
f=int(input("Marks of student 6="))
M=[a,b,c,d,e,f]
print(M)
M.sort()
print(M)