n1=int(input("Enter number1:"))
n2=int(input("Enter number2:"))
n3=int(input("Enter number3:"))
n4=int(input("Enter number4:"))
n5=int(input("Enter number5:"))
s={n1,n2,n3,n4,n5}
print(s)

s.add(20)
s.add((45,30,20))
print(s)
s.pop()
s.remove(20)
print(s)
s=s.union({0,1,2,3,4,5})
print(s)
s=s.intersection({0,1,2,3,4})
print(s)
s.clear()
print(s)